// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Pi8raqG88DNcjX8YaWgl5qOi-aR3vLc',
    appId: '1:122489390373:web:7c2678e2ee58f27e5446cc',
    messagingSenderId: '122489390373',
    projectId: 'image-f70ce',
    authDomain: 'image-f70ce.firebaseapp.com',
    storageBucket: 'image-f70ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4LHeLT130YfPSeDQocAkcp9vfj8kRilA',
    appId: '1:122489390373:android:a45fd94413289a5c5446cc',
    messagingSenderId: '122489390373',
    projectId: 'image-f70ce',
    storageBucket: 'image-f70ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5iDp6-3hBIKKm6hmgEz0NpiSjN4x6vtg',
    appId: '1:122489390373:ios:6d1158999e7fa3cd5446cc',
    messagingSenderId: '122489390373',
    projectId: 'image-f70ce',
    storageBucket: 'image-f70ce.appspot.com',
    iosClientId: '122489390373-8p5nfgcct47ng2alfjsalb6m7rq87fjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.imageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5iDp6-3hBIKKm6hmgEz0NpiSjN4x6vtg',
    appId: '1:122489390373:ios:6d1158999e7fa3cd5446cc',
    messagingSenderId: '122489390373',
    projectId: 'image-f70ce',
    storageBucket: 'image-f70ce.appspot.com',
    iosClientId: '122489390373-8p5nfgcct47ng2alfjsalb6m7rq87fjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.imageapp',
  );
}
